/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/leads' | '/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/leads' | '/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/leads'
    | '/_authenticated/leads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
  }
}

interface AuthenticatedLeadsRouteChildren {
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
}

const AuthenticatedLeadsRouteChildren: AuthenticatedLeadsRouteChildren = {
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
}

const AuthenticatedLeadsRouteWithChildren =
  AuthenticatedLeadsRoute._addFileChildren(AuthenticatedLeadsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLeadsRoute: AuthenticatedLeadsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
